# Generated by Django 6.0.1 on 2026-01-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('milestone', 'Milestone'), ('action', 'Action')], default='info', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='missions.mission')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mission', '-timestamp'], name='activities__mission_99fbcf_idx'), models.Index(fields=['type'], name='activities__type_a1420f_idx')],
            },
        ),
    ]
